/* eslint-disable jsx-a11y/label-has-associated-control */

'use client';

import { useId, useState } from 'react';

import { Button } from '../components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '../components/ui/dialog';
import { cn } from '../lib/utils';

import styles from './page.module.css';

// eslint-disable-next-line @typescript-eslint/require-await
export default function Index() {
  const [ value, setValue ] = useState('');
  const elementId = useId();

  return (
    <div className={styles.page}>
      <h1>Welcome to web!</h1>
      <p>Generated by create-nx-workspace</p>
      <div className="w-[28px] h-[28px] bg-black rounded-full mx-auto" />

      <main className="flex flex-col gap-y-2 p-4">
        <div className="relative w-full h-[50px] bg-gray-100 rounded-lg">
          <input
            className="peer w-full h-[50px] rounded-lg"
            id={elementId}
            onChange={(e) => setValue(e.target.value)}
            type="password"
            value={value}
          />
          <label
            className={cn(
              'peer-focus:top-0 peer-focus:left-2 peer-focus:text-xs peer-focus:bg-white peer-focus:px-2',
              'peer-focus:absolute peer-focus:font-medium transition-all peer',
              'absolute top-1/2 left-2 transform -translate-y-1/2 text-gray-400 font-medium',
              value ? 'top-0 left-2 text-xs bg-white px-2' : '',
            )}
            htmlFor={elementId}
          >
            Label
            <span className="text-red-500"> *</span>
          </label>
        </div>
        <div className="relative w-full h-[50px] bg-gray-100 rounded-lg">
          <input
            className="peer w-full h-[50px] rounded-lg"
            id={elementId}
            onChange={(e) => setValue(e.target.value)}
            type="password"
            value={value}
          />
          <label
            className={cn(
              'peer-focus:top-0 peer-focus:left-2 peer-focus:text-xs peer-focus:bg-white peer-focus:px-2',
              'peer-focus:absolute peer-focus:font-medium transition-all peer',
              'absolute top-1/2 left-2 transform -translate-y-1/2 text-gray-400 font-medium',
              value ? 'top-0 left-2 text-xs bg-white px-2' : '',
            )}
            htmlFor={elementId}
          >
            Label
            <span className="text-red-500"> *</span>
          </label>
        </div>
        <footer className="flex justify-between gap-x-4 w-full p-4 bg-gray-100 rounded-lg">
          <Button>Button</Button>
          <Button variant="destructive">Button</Button>
        </footer>
      </main>
      <Dialog>
        <DialogTrigger>Open</DialogTrigger>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Are you absolutely sure?</DialogTitle>
            <DialogDescription>
              This action cannot be undone. This will permanently delete your account
              and remove your data from our servers.
            </DialogDescription>
          </DialogHeader>
        </DialogContent>
      </Dialog>
    </div>
  );
}
