import styles from './page.module.css';

// eslint-disable-next-line @typescript-eslint/require-await
export default async function Index() {
  return (
    <div className={styles.page}>
      <h1>Welcome to web!</h1>
      <p>Generated by create-nx-workspace</p>
    </div>
  );
}
